### ISSUE TITLE
Everything is broken

### ISSUE THREAD

**Issue by ThePixelBro22** [satori/go.uuid#67] opened 2018-01-04 06:12 UTC
After this sudden change, everything in my code will NOT work. Not even build with docker 
 
All I get is this `multiple-value uuid.NewV4() in single-value context`

**Comment by callmeErgou** [comment] 2018-01-04 09:20
me too ......

**Comment by mpecan** [comment] 2018-01-04 10:03
```go
uuid := uuid.NewV4()
``` 
changes to
```go
uuid, err := uuid.NewV4()
```

I have the same issue, but the new format actually complies with the Go guidelines better, so I guess we will just have to change and adapt.

**Comment by snedzad** [comment] 2018-01-04 14:00
If the reason is really the need for compliance it's a terrible one. It's breaking everyone's code just to have some compliance achieved. You should've made v2 and make changes there.

**Comment by ivucica** [comment] 2018-01-04 14:33
See also original bug https://github.com/satori/go.uuid/issues/18 and maybe consider continuing this discussion in https://github.com/satori/go.uuid/issues/66

**Comment by kataras** [comment] 2018-01-04 19:10
@satori Can you create a branch based on that commit: [5bf94b69c6b68ee1b541973bb8e1144db23a194b]( https://github.com/satori/go.uuid/commit/5bf94b69c6b68ee1b541973bb8e1144db23a194b)? This will fix some issues that `dep` users have with [iris](https://github.com/kataras/iris) (although Iris vendored the go.uuid and has not any problems for its session databases or internal packages but `dep` tool doesn't care about the `.lock` file there) so I have to update the gopkg.toml with branch="v1.2.0" I propose you to create which will point before that breaking API, thank you very much!

**Comment by grugnog** [comment] 2018-01-05 17:30
Also seeing fails on:

**Comment by satori** [comment] 2018-01-10 19:19
Closing as a duplicate of #66 

@kataras I've tagged v1.2.0 as last commit before API has changed but contains some bug fixes and improvements.

**Closed by satori** 2018-01-10 19:19 UTC
