### ISSUE TITLE
Add IsZero method

### ISSUE THREAD

**Issue by vmihailenco** [satori/go.uuid#49] opened 2017-05-16 15:28 UTC
Hi,

What do you think about adding `IsZero` method to UUID type? This is needed for [go-pg](https://github.com/go-pg/pg/issues/537) to check if uuid does not have any value and generate

```
INSERT INTO table (uuid) VALUES (DEFAULT)
```

instead of

```
INSERT INTO table (uuid) VALUES ('00000000-0000-0000-0000-000000000000')
```

I already do this for `time.Time` and it works well. I can send PR if you don't mind.

**Comment by apkrieg** [comment] 2017-09-25 14:47
I don't think adding functions to support 3rd-party libraries is a good idea. The issue is closed now I see.

**Comment by dalu** [comment] 2017-10-14 17:41
cool, not using this package then

**Comment by satori** [comment] 2018-01-03 01:13
What you are trying to achieve is the **absence of value** represented by NULL in SQL standard, while Nil UUID from RFC states for a **zero value** of UUID. You can find further discussion in #23 and try using `NullUUID` instead which is designed specifically for sql package.

Interpreting a zero value as absent value is fundamental mistake.

**Comment by satori** [comment] 2018-01-03 01:25
Closing for the same reason as other `IsZero` PRs.

**Closed by satori** 2018-01-03 01:25 UTC
